### ISSUE TITLE
这个问题怎么解决

### ISSUE THREAD

**Issue by Rs529811807** [yeyupiaoling/PaddlePaddle-DeepSpeech#115]
Traceback (most recent call last):
  File "infer_path.py", line 5, in <module>
    from data_utils.audio_process import AudioInferProcess
  File "D:\wenanyuyin\PaddlePaddle-DeepSpeech\data_utils\audio_process.py", line 2, in <module>
    from data_utils.normalizer import FeatureNormalizer
  File "D:\wenanyuyin\PaddlePaddle-DeepSpeech\data_utils\normalizer.py", line 7, in <module>
    from paddle.io import Dataset, DataLoader
  File "C:\ProgramData\Anaconda3\envs\py370\lib\site-packages\paddle\io\__init__.py", line 19, in <module>
    from ..fluid.dataloader import IterableDataset  # noqa: F401
ImportError: cannot import name 'IterableDataset' from 'paddle.fluid.dataloader' (C:\ProgramData\Anaconda3\envs\py370\lib\site-packages\paddle\fluid\dataloader\__init__.py)

**Comment by Rs529811807** [comment]
相关依赖也安装后，执行就出现这个问题

**Comment by yeyupiaoling** [comment]
你的PaddlePaddle版本是多少
