### ISSUE TITLE
执行export_model.py时候报错

### ISSUE THREAD

**Issue by AryaStar** [yeyupiaoling/PaddlePaddle-DeepSpeech#119]
您好！
program.set_state_dict(load_state_dict)这一句：
TypeError: Type of `state_dict` should be dict, but received <class 'paddle.Tensor'>.
请问应该怎么解决

**Comment by yeyupiaoling** [comment]
谢谢！已收到您的邮件，祝您开心每一天

**Comment by yeyupiaoling** [comment]
你是使用我提供下载的模型吗？

**Comment by yeyupiaoling** [comment]
你提供更多的错误信息看看

**Comment by AryaStar** [comment]
谢谢您，我使用的是这个链接https://download.csdn.net/download/qq_33200967/21773253?utm_medium=distribute.pc_relevant_download.none-task-download-2~default~OPENSEARCH~default-3.test_version_3&depth_1-utm_source=distribute.pc_relevant_download.none-task-download-2~default~OPENSEARCH~default-3.test_version_3&dest=https%3A%2F%2Fdownload.csdn.net%2Fdownload%2Fqq_33200967%2F21773253&spm=1003.2020.3001.6616.3下载的模型\models\step_final\params.pdparams

然后我使用了老版本的release执行export_model.py成功实现了
但是我使用新版本的master分支执行export_model.py失败了

具体报错如下：
Traceback (most recent call last):
  File ".\export_model.py", line 32, in <module>
    ds2_model.export_model(model_path=args.save_model_path)
  File "C:\Users\CS8DA\Desktop\PaddlePaddle-DeepSpeech-master\model_utils\model.py", line 438, in export_model
    self.load_param(self.infer_program, self._resume_model)
  File "C:\Users\CS8DA\Desktop\PaddlePaddle-DeepSpeech-master\model_utils\model.py", line 150, in load_param
    program.set_state_dict(load_state_dict)
  File "E:\ProgramData\Anaconda3\envs\myaudio\lib\site-packages\paddle\fluid\framework.py", line 5804, in set_state_dict
    type(state_dict)))
TypeError: Type of `state_dict` should be dict, but received <class 'paddle.fluid.core_avx.LoDTensor'>.

**Comment by AryaStar** [comment]
谢谢您，我使用的是这个链接https://download.csdn.net/download/qq_33200967/21773253?utm_medium=distribute.pc_relevant_download.none-task-download-2~default~OPENSEARCH~default-3.test_version_3&depth_1-utm_source=distribute.pc_relevant_download.none-task-download-2~default~OPENSEARCH~default-3.test_version_3&dest=https%3A%2F%2Fdownload.csdn.net%2Fdownload%2Fqq_33200967%2F21773253&spm=1003.2020.3001.6616.3

下载的模型\models\step_final\params.pdparams

然后我使用了老版本的release执行export_model.py成功实现了
但是我使用新版本的master分支执行export_model.py失败了

具体报错如下：
Traceback (most recent call last):
File ".\export_model.py", line 32, in
ds2_model.export_model(model_path=args.save_model_path)
File "C:\Users\CS8DA\Desktop\PaddlePaddle-DeepSpeech-master\model_utils\model.py", line 438, in export_model
self.load_param(self.infer_program, self._resume_model)
File "C:\Users\CS8DA\Desktop\PaddlePaddle-DeepSpeech-master\model_utils\model.py", line 150, in load_param
program.set_state_dict(load_state_dict)
File "E:\ProgramData\Anaconda3\envs\myaudio\lib\site-packages\paddle\fluid\framework.py", line 5804, in set_state_dict
type(state_dict)))
TypeError: Type of state_dict should be dict, but received <class 'paddle.fluid.core_avx.LoDTensor'>.

**Comment by AryaStar** [comment]
谢谢您，我使用的是这个链接https://download.csdn.net/download/qq_33200967/21773253?utm_medium=distribute.pc_relevant_download.none-task-download-2~default~OPENSEARCH~default-3.test_version_3&depth_1-utm_source=distribute.pc_relevant_download.none-task-download-2~default~OPENSEARCH~default-3.test_version_3&dest=https%3A%2F%2Fdownload.csdn.net%2Fdownload%2Fqq_33200967%2F21773253&spm=1003.2020.3001.6616.3

下载的模型\models\step_final\params.pdparams

然后我使用了老版本的release执行export_model.py成功实现了
但是我使用新版本的master分支执行export_model.py失败了

具体报错如下：
Traceback (most recent call last):
File ".\export_model.py", line 32, in
ds2_model.export_model(model_path=args.save_model_path)
File "C:\Users\CS8DA\Desktop\PaddlePaddle-DeepSpeech-master\model_utils\model.py", line 438, in export_model
self.load_param(self.infer_program, self._resume_model)
File "C:\Users\CS8DA\Desktop\PaddlePaddle-DeepSpeech-master\model_utils\model.py", line 150, in load_param
program.set_state_dict(load_state_dict)
File "E:\ProgramData\Anaconda3\envs\myaudio\lib\site-packages\paddle\fluid\framework.py", line 5804, in set_state_dict
type(state_dict)))
TypeError: Type of state_dict should be dict, but received <class 'paddle.fluid.core_avx.LoDTensor'>.

**Comment by yeyupiaoling** [comment]
老版本和新版本的模型不通用的，请在对应页面重新下载。

**Comment by AryaStar** [comment]
谢谢您，已成功export_model
