### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (161,838) (39,1)

### ISSUE THREAD

**Issue by harryNLP** [yeyupiaoling/PaddlePaddle-DeepSpeech#145]
I am running the demo follow your instructions but encounter a problem, the error message is shown as follows. My operating system is Macos 

 python3  infer_path.py --wav_path=./dataset/test.wav
-----------  Configuration Arguments -----------
alpha: 1.2
beam_size: 300
beta: 0.35
cutoff_prob: 0.99
cutoff_top_n: 40
decoding_method: ctc_greedy
enable_mkldnn: False
is_long_audio: False
lang_model_path: ./lm/zh_giga.no_cna_cmn.prune01244.klm
mean_std_path: ./dataset/mean_std.npz
model_dir: ./models/infer/
to_an: True
use_gpu: False
vocab_path: ./dataset/zh_vocab.txt
wav_path: ./dataset/test.wav
------------------------------------------------
E0520 19:05:52.228500 471705088 analysis_config.cc:95] Please compile with gpu to EnableGpu()
Traceback (most recent call last):
  File "/Users/huanghaowei/Downloads/PaddlePaddle-DeepSpeech-master/infer_path.py", line 34, in <module>
    predictor = Predictor(model_dir=args.model_dir, audio_process=audio_process, decoding_method=args.decoding_method,
  File "/Users/huanghaowei/Downloads/PaddlePaddle-DeepSpeech-master/utils/predict.py", line 69, in __init__
    self.predict(warmup_audio_path, to_an=True)
  File "/Users/huanghaowei/Downloads/PaddlePaddle-DeepSpeech-master/utils/predict.py", line 76, in predict
    audio_feature = self.audio_process.process_utterance(audio_path)
  File "/Users/huanghaowei/Downloads/PaddlePaddle-DeepSpeech-master/data_utils/audio_process.py", line 44, in process_utterance
    specgram = self._normalizer.apply(specgram)
  File "/Users/huanghaowei/Downloads/PaddlePaddle-DeepSpeech-master/data_utils/normalizer.py", line 55, in apply
    return (features - self._mean) / (self._std + eps)
ValueError: operands could not be broadcast together with shapes (161,838) (39,1)

**Comment by yeyupiaoling** [comment]
你下载的模型文件有没有全部替换原来的了，注意是dataset里面的文件
