### ISSUE TITLE
使用create_data时候对noise数据进行处理时，出现报错未能产生均值归一化方差的npz文件，请问这个可以怎么解决？

### ISSUE THREAD

**Issue by xuhongtian** [yeyupiaoling/PaddlePaddle-DeepSpeech#151]
使用create_data时候对noise数据进行处理时，出现报错未能产生均值归一化方差的npz文件
报错如下：
Traceback (most recent call last):
  File "/data/wav_ocr/paddle_deepspeech/create_data.py", line 223, in <module>
    main()
  File "/data/wav_ocr/paddle_deepspeech/create_data.py", line 218, in main
    compute_mean_std(args.manifest_paths, args.num_samples, args.output_path)
  File "/data/wav_ocr/paddle_deepspeech/create_data.py", line 183, in compute_mean_std
    normalizer = FeatureNormalizer(mean_std_filepath=None,
  File "/data/wav_ocr/paddle_deepspeech/data_utils/normalizer.py", line 41, in __init__
    self._compute_mean_std(manifest_path, num_samples, num_workers)
  File "/data/wav_ocr/paddle_deepspeech/data_utils/normalizer.py", line 94, in _compute_mean_std
    for i in range(len(means)):
TypeError: object of type 'NoneType' has no len()

**Comment by yeyupiaoling** [comment]
噪声数据是不需要生成归一化文件的。你看你的训练数据列表有没有数据。

**Comment by xuhongtian** [comment]
刚看了下我的manifest.train为空
