### ISSUE TITLE
本地预测时找不到打不开文件

### ISSUE THREAD

**Issue by Jackdfse** [yeyupiaoling/PaddlePaddle-DeepSpeech#169]
![Uploading 图片1.png…]()

(NotFound) Cannot open file C:\Users\帅哥\AppData\Roaming\Python\Python39\site-packages\LAC\lac_model\model/__model__, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at C:\home\workspace\Paddle_release\paddle\fluid\inference\api\analysis_predictor.cc:953)

Traceback (most recent call last):
  File "C:\Users\帅哥\Desktop\daima\PaddlePaddle-DeepSpeech-master\infer_path.py", line 34, in <module>
    predictor = Predictor(model_dir=args.model_dir, audio_process=audio_process, decoding_method=args.decoding_method,
  File "C:\Users\帅哥\Desktop\daima\PaddlePaddle-DeepSpeech-master\utils\predict.py", line 69, in __init__
    self.predict(warmup_audio_path, to_an=True)
  File "C:\Users\帅哥\Desktop\daima\PaddlePaddle-DeepSpeech-master\utils\predict.py", line 122, in predict
    text = self.cn2an(text)
  File "C:\Users\帅哥\Desktop\daima\PaddlePaddle-DeepSpeech-master\utils\predict.py", line 129, in cn2an
    self.lac = LAC(mode='lac', use_cuda=self.use_gpu)
  File "C:\Users\帅哥\AppData\Roaming\Python\Python39\site-packages\LAC\lac.py", line 78, in __init__
    self.predictor = create_paddle_predictor(config)
RuntimeError: Unknown exception

**Comment by Jackdfse** [comment]
大佬救救
！！！

**Comment by Jackdfse** [comment]
文件什么也都有，就是报错

**Comment by yeyupiaoling** [comment]
用我的PPASR，这个新一些，同样有deepspeech
