### ISSUE TITLE
训练代码时，报AttributeError: 'tuple' object has no attribute 'shape'的错误

### ISSUE THREAD

**Issue by lsx193201** [yeyupiaoling/PaddlePaddle-DeepSpeech#175]
我的python版本为3.7，安装的paddlepaddle版本为paddlepaddle-rocm   0.0.0，该paddlepaddle版本适配于我的超算平台，能够使用加速卡进行加速，已完成对WenetSpeech数据集的标注和训练数据集的制作，到最后一步训练模型时运行命令：CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py，报下面的错误：
W1112 11:38:24.614019   977 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 90.0, Driver API Version: 50400.0, Runtime API Version: 50400.0
W1112 11:38:25.305178   977 device_context.cc:460] device: 0, MIOpen Version: 2.15.3
/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
<class 'list'>
/public/home/oliver7417/paddle/PaddlePaddle-DeepSpeech-master/utils/summary.py:177: UserWarning: Get layer {} input shape failed!
  warnings.warn('Get layer {} input shape failed!')
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    train()
  File "train.py", line 107, in train
    summary(model, inputs=input_data)
  File "/public/home/oliver7417/paddle/PaddlePaddle-DeepSpeech-master/utils/summary.py", line 112, in summary
    result, params_info = summary_string(net, _input_size, dtypes, inputs)
  File "/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 351, in _decorate_function
    return func(*args, **kwargs)
  File "/public/home/oliver7417/paddle/PaddlePaddle-DeepSpeech-master/utils/summary.py", line 242, in summary_string
    model(*x)
  File "/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/public/home/oliver7417/paddle/PaddlePaddle-DeepSpeech-master/model_utils/model.py", line 83, in forward
    print(type(self.rnn[i](x, sequence_length=x_lens)))
  File "/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1064, in forward
    self.state_components)
  File "/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 77, in split_states
    states = paddle.unstack(states)
  File "/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 10336, in unstack
    num = x.shape[axis]
AttributeError: 'tuple' object has no attribute 'shape'
我修改返回了train.py文件中的input_data的类型为list，说明数据加载进去了，我觉得可能时self.rnn[i](x, sequence_length=x_lens）这部分存在一些问题，但是却不知道问题存在哪里，还是说这个训练是依赖于GPU训练，不支持DCU进行训练，还望解答

**Comment by lsx193201** [comment]
暂时已解决，我把/public/home/oliver7417/.conda/envs/paddle37/lib/python3.7/site-packages/paddle/fluid/layers/nn.py的x转化为了tensor，能够开始训练阶段，就是不知道是否会对我接下来的训练产生影响。
