### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by laitianan** [yeyupiaoling/PaddlePaddle-DeepSpeech#52]
本地安装含有两处一直不明白的错误，1.安装后一直执行一直出现以下错误：
Traceback (most recent call last):
  File "train.py", line 5, in <module>
    from model_utils.model import DeepSpeech2Model
  File "/home/pysourcecode/PaddlePaddle-DeepSpeech-master/model_utils/model.py", line 14, in <module>
    from ctc_decoders.swig_wrapper import Scorer
  File "/home/anaconda3/envs/deepspeech/lib/python3.7/site-packages/swig_decoders-1.1-py3.7-linux-x86_64.egg/ctc_decoders/swig_wrapper.py", line 3, in <module>
    import swig_decoders
ModuleNotFoundError: No module named 'swig_decoders'
2. 进入到 cd decoders,执行sh setup.sh ,出现错误为:decoder_utils.h:55: Error: Syntax error in input(1)
(麻烦指导下这个环境，本人环境未centos,其他的都是一样的执行操作，把apt-get修改为了yum ).

**Comment by yeyupiaoling** [comment]
我也没遇到这种情况，Ubuntu编译是正常的。有详细的错误提示吗？

**Comment by yeyupiaoling** [comment]
最新的代码不需要编译swig_decoders这个了，你可以拉取最新的代码试试。
