### ISSUE TITLE
OSError 'sndfile'

### ISSUE THREAD

**Issue by jialesmu** [yeyupiaoling/PaddlePaddle-DeepSpeech#56]
docker~~~python create_manifest.py 
Traceback (most recent call last):
  File "create_manifest.py", line 13, in <module>
    from utils.utility import add_arguments, print_arguments, change_rate
  File "/home/DeepSpeech/utils/utility.py", line 5, in <module>
    import librosa
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/soundfile.py", line 267, in <module>
    _snd = _ffi.dlopen('sndfile')
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called `sndfile`

system uses ubuntu 2004, and running program in docker with paddle:2.1.1-gpu-cuda10.2-cudnn7

**Comment by yeyupiaoling** [comment]
@jialesmu 你看看这个是否能解决你的问题：https://stackoverflow.com/questions/56974700/in-docker-oserror-ctypes-util-find-library-did-not-manage-to-locate-a-libra
或者你试试在本地搭建环境。

**Comment by jialesmu** [comment]
> @jialesmu 你看看这个是否能解决你的问题：https://stackoverflow.com/questions/56974700/in-docker-oserror-ctypes-util-find-library-did-not-manage-to-locate-a-libra
> 或者你试试在本地搭建环境。

谢谢，问题已经解决～
