### ISSUE TITLE
 Bug请教:`CUBLAS_STATUS_NOT_INITIALIZED`

### ISSUE THREAD

**Issue by psuu0001** [yeyupiaoling/PaddlePaddle-DeepSpeech#63]
Traceback (most recent call last):
  File "infer_path.py", line 40, in <module>
    use_tensorrt=args.use_tensorrt, enable_mkldnn=args.enable_mkldnn)
  File "/PaddlePaddle-DeepSpeech-release-1.0/utils/predict.py", line 68, in __init__
    self.predict(warmup_audio_path)
  File "/PaddlePaddle-DeepSpeech-release-1.0/utils/predict.py", line 93, in predict
    self.audio_data_handle.copy_from_cpu(audio_data)
OSError: (External)  Cublas error, `CUBLAS_STATUS_NOT_INITIALIZED`. The cuBLAS library was not initialized.
请问这个bug是哪里来的呢

**Comment by yeyupiaoling** [comment]
这应该是CUDA的错误？可能是你的版本没有对应上。
